package ar.edu.unlu.poo.MODELO;

public enum Evento {
    JUGADOR_CONECTADO,
    INICIAR_PARTIDA,
    CAMBIOS_PARTIDA,
    ERROR_POSICIONES,
    PASO_TURNO,
    ERROR_CAMBIO,
    ERROR_FICHAS_ATRIL,
    FICHAS_CAMBIADAS,
    ERROR_CENTRO,
    ERROR_DICCIONARIO,
    ERROR_ADYACENTES,
    CELDA_OCUPADA,
    FIN_PARTIDA,
    PALABRA_AGREGADA,
    PARTIDA_GUARDADA;
}
